{{- with .Values.chatui }}
{{- if .route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "llama-stack-chatui.fullname" $ }}
  {{- with .route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .route.host }}
  host: {{ .route.host }}
  {{- end }}
  {{- if .route.path }}
  path: {{ .route.path }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "llama-stack-chatui.fullname" $ }}
    weight: 100
  port:
    targetPort: llama-stack-chatui
  {{- if .route.tls.enabled }}
  tls:
    termination: {{ .route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
{{- end }}