{{- with .Values.mcpKubernetes }}
# TODO: In the future this should probably be its own chart
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-server-kube.fullname" $ }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "mcp-server-kube.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mcp-server-kube.selectorLabels" $ | nindent 8 }}
    spec:
      serviceAccountName: kube-mcp-sa
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mcp-server-kube
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}