apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-mcp-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-rolebinding
subjects:
  - kind: ServiceAccount
    name: kube-mcp-sa
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: view-role
  apiGroup: rbac.authorization.k8s.io